[[colors.indexed_colors]]
color = "#ffa066"
index = 16

[[colors.indexed_colors]]
color = "#ff5d62"
index = 17

[[colors.indexed_colors]]
color = "#3c3836"
index = 18

[[colors.indexed_colors]]
color = "#504945"
index = 19

[[colors.indexed_colors]]
color = "#bdae93"
index = 20

[[colors.indexed_colors]]
color = "#ebdbb2"
index = 21

[colors.bright]
black = "0x727169"
blue = "0x7fb4ca"
cyan = "0x7aa89f"
green = "0x98bb6c"
magenta = "0x938aa9"
red = "0xe82424"
white = "0xdcd7ba"
yellow = "0xe6c384"

[colors.cursor]
cursor = "0xdcd7ba"
text = "0x1f1f28"

[colors.normal]
black = "0x090618"
blue = "0x7e9cd8"
cyan = "0x6a9589"
green = "0x76946a"
magenta = "0x957fb8"
red = "0xc34043"
white = "0xc8c093"
yellow = "0xc0a36e"

[colors.primary]
background = "0x1f1f28"
foreground = "0xdcd7ba"

[env]
TERM = "xterm-256color"

[font]
size = 14
normal = { family = "Berkeley Mono", style = "Regular" }
bold = { family = "Berkeley Mono", style = "Bold" }
italic = { family = "Berkeley Mono", style = "Italic" }
bold_italic = { family = "Berkeley Mono", style = "Bold Italic" }

[window]
dynamic_title = false
title = "Terminal"

[window.padding]
x = 6
