[colors.primary]
background = "#161616"
foreground = "#ffffff"

[colors.search]
matches = { foreground = "CellBackground", background = "#ee5396"}

[colors.footer_bar]
foreground = "#ffffff"
background = "#262626"

[colors.normal]
black = "#262626"
magenta = "#ff7eb6"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
red = "#ee5396"
cyan = "#3ddbd9"
white = "#dde1e6"

[colors.bright]
black = "#393939"
magenta = "#ff7eb6"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
red = "#ee5396"
cyan = "#3ddbd9"
white = "#ffffff"

[env]
TERM = "xterm-256color"

[font]
size = 14
normal = { family = "Berkeley Mono", style = "Regular" }
bold = { family = "Berkeley Mono", style = "Bold" }
italic = { family = "Berkeley Mono", style = "Italic" }
bold_italic = { family = "Berkeley Mono", style = "Bold Italic" }

[window]
dynamic_title = false
title = "Terminal"

[window.padding]
x = 6
y = 4
