#!/usr/bin/env bash

if [ $(setxkbmap -query | grep -c "variant") -eq 0 ]; then
    setxkbmap us -variant intl
    notify-send "Keyboard Layout" "US International"
else
    setxkbmap us
    notify-send "Keyboard Layout" "US"
fi
