local set = vim.keymap.set

set("v", "J", ":m '>+1<CR>gv=gv")
set("v", "K", ":m '<-2<CR>gv=gv")
set("n", "J", "mzJ`z")
set("n", "<C-d>", "<C-d>zz")
set("n", "<C-u>", "<C-u>zz")
set("n", "n", "nzzzv")
set("n", "N", "Nzzzv")
set({ "n", "v" }, "<leader>y", [["+y]])
set("n", "<leader>Y", [["+Y]])
set('n', '<Esc>', '<cmd>nohlsearch<CR>')
set('t', '<Esc><Esc>', '<C-\\><C-n>')
set('n', '<C-h>', '<C-w><C-h>')
set('n', '<C-l>', '<C-w><C-l>')
set('n', '<C-j>', '<C-w><C-j>')
set('n', '<C-k>', '<C-w><C-k>')
set("n", "<C-n>", "<CMD>Oil<CR>")
